# Generated by Django 5.2.2 on 2025-08-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nws_id', models.CharField(max_length=255, unique=True)),
                ('event', models.CharField(max_length=255)),
                ('headline', models.TextField()),
                ('area_desc', models.TextField()),
                ('effective', models.DateTimeField()),
                ('expires', models.DateTimeField(blank=True, null=True)),
                ('geojson', models.JSONField()),
            ],
        ),
    ]
